server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/city?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: lyc1289choose
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    root: info
    com:
      nit:
        city:
          dao: debug
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.nit.bean